// MojoBoost — mods-data.js
// Complete mod database

const MODS_DB = [
  {
    id: "sodium",
    name: "Sodium",
    icon: "⚡",
    shortDesc: "The gold standard rendering engine replacement. Massive FPS gains on all devices.",
    description: "Sodium is a free and open-source rendering engine replacement for the Minecraft client that greatly improves frame rates and fixes graphical issues. It replaces Minecraft's built-in chunk rendering pipeline with a modern, optimized one that can achieve 2–5× higher frame rates on the same hardware.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "NeoForge"],
    category: "rendering",
    performanceRating: 98,
    memoryUsage: "low",
    memoryMB: -64,
    fpsGain: { min: 80, max: 300, avg: 150 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 99,
    downloadUrl: "https://modrinth.com/mod/sodium",
    installInstructions: "Download the .jar from Modrinth and place it in your .minecraft/mods folder. Requires Fabric or Quilt loader.",
    tags: ["rendering", "fps", "performance", "essential"],
    featured: true
  },
  {
    id: "lithium",
    name: "Lithium",
    icon: "🔋",
    shortDesc: "Game logic and server-side optimizations. Reduces CPU overhead significantly.",
    description: "Lithium is a general-purpose optimization mod for Minecraft which works to improve a number of systems (game physics, mob AI, block ticking, etc.) without changing any behavior. It targets the server-side simulation, making both singleplayer and multiplayer smoother.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "logic",
    performanceRating: 85,
    memoryUsage: "low",
    memoryMB: -32,
    fpsGain: { min: 10, max: 40, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 95,
    downloadUrl: "https://modrinth.com/mod/lithium",
    installInstructions: "Download from Modrinth. Works alongside Sodium. No configuration needed — improvements are automatic.",
    tags: ["logic", "cpu", "performance", "essential"],
    featured: true
  },
  {
    id: "ferritecore",
    name: "FerriteCore",
    icon: "🧲",
    shortDesc: "Dramatically reduces memory usage. Essential for low-RAM Android devices.",
    description: "FerriteCore reduces the memory usage of Minecraft in a number of different ways. Some of these changes also improve the game's frame rate, but its primary goal is to reduce memory consumption — often by 500 MB to 1 GB. Absolutely essential for devices with 2–4 GB RAM.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "memory",
    performanceRating: 90,
    memoryUsage: "very-low",
    memoryMB: -512,
    fpsGain: { min: 5, max: 30, avg: 15 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 93,
    downloadUrl: "https://modrinth.com/mod/ferrite-core",
    installInstructions: "Drop the .jar in your mods folder. Works with Fabric, Forge, and NeoForge. Reduces RAM usage immediately on launch.",
    tags: ["memory", "ram", "performance", "essential", "mobile"],
    featured: true
  },
  {
    id: "modernfix",
    name: "ModernFix",
    icon: "🔧",
    shortDesc: "Fixes dozens of performance bugs. Faster world loading and startup times.",
    description: "ModernFix is an all-in-one mod that improves performance, reduces memory usage, and fixes many bugs in modern Minecraft versions. It speeds up game startup, world loading, and chunk generation while also patching memory leaks and other performance issues introduced in newer Minecraft versions.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge", "NeoForge"],
    category: "general",
    performanceRating: 88,
    memoryUsage: "low",
    memoryMB: -256,
    fpsGain: { min: 15, max: 60, avg: 30 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 88,
    downloadUrl: "https://modrinth.com/mod/modernfix",
    installInstructions: "Place in mods folder. Configuration available via ModernFix's config file to enable/disable specific fixes.",
    tags: ["general", "startup", "memory", "essential"],
    featured: true
  },
  {
    id: "immediatelyfast",
    name: "ImmediatelyFast",
    icon: "⚡",
    shortDesc: "Optimizes immediate-mode rendering. Huge gains in UI and entity rendering.",
    description: "ImmediatelyFast is a mod that improves the immediate-mode rendering performance of Minecraft. It optimizes how entities, GUI elements, and other objects are rendered using immediate-mode rendering, which is heavily used in Minecraft. Works great alongside Sodium.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "NeoForge"],
    category: "rendering",
    performanceRating: 82,
    memoryUsage: "low",
    memoryMB: -16,
    fpsGain: { min: 20, max: 80, avg: 40 },
    compatibility: { arm64: true, arm32: false, x86: true },
    minAndroid: 10,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced", "Best Graphics"],
    popularity: 85,
    downloadUrl: "https://modrinth.com/mod/immediatelyfast",
    installInstructions: "Requires Sodium on Fabric. Drop in mods folder. Best combined with Sodium + Lithium for maximum effect.",
    tags: ["rendering", "entities", "gui", "fps"],
    featured: false
  },
  {
    id: "entityculling",
    name: "EntityCulling",
    icon: "👁️",
    shortDesc: "Skips rendering entities you can't see. Massive FPS boost in populated areas.",
    description: "EntityCulling uses async path-tracing to determine which entities are visible. Hidden entities (behind walls, underground, etc.) are skipped entirely during rendering. This provides enormous FPS gains in areas with many entities, mobs, or players.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "rendering",
    performanceRating: 87,
    memoryUsage: "low",
    memoryMB: -8,
    fpsGain: { min: 15, max: 100, avg: 35 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 86,
    downloadUrl: "https://modrinth.com/mod/entityculling",
    installInstructions: "Place in mods folder. Works on Fabric and Forge. Configuration available for culling aggressiveness.",
    tags: ["rendering", "entities", "culling", "fps"],
    featured: false
  },
  {
    id: "dynamicfps",
    name: "Dynamic FPS",
    icon: "🔋",
    shortDesc: "Reduces FPS when game is unfocused. Saves battery life on mobile.",
    description: "Dynamic FPS automatically reduces Minecraft's frame rate when the app is not in focus, and can completely pause rendering when minimized. This saves significant battery life on Android devices, making it an essential mod for mobile Minecraft players.",
    versions: ["1.14", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "battery",
    performanceRating: 75,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 10, avg: 5 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Battery Saver", "Balanced"],
    popularity: 80,
    downloadUrl: "https://modrinth.com/mod/dynamic-fps",
    installInstructions: "Drop in mods folder. Configure idle FPS limit in the mod's config. Recommended: 1 FPS when minimized, 30 when unfocused.",
    tags: ["battery", "mobile", "background", "power"],
    featured: false
  },
  {
    id: "noisium",
    name: "Noisium",
    icon: "🌍",
    shortDesc: "Speeds up world generation noise calculations. Faster chunk loading.",
    description: "Noisium optimizes world generation by speeding up the noise calculations used to generate terrain. This results in significantly faster chunk loading and world generation, particularly noticeable when exploring new areas or generating new worlds.",
    versions: ["1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "worldgen",
    performanceRating: 78,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 5, max: 25, avg: 12 },
    compatibility: { arm64: true, arm32: false, x86: true },
    minAndroid: 10,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 72,
    downloadUrl: "https://modrinth.com/mod/noisium",
    installInstructions: "Place in mods folder on Fabric or Quilt. Most noticeable improvement when generating new chunks in 1.20+.",
    tags: ["worldgen", "chunks", "terrain", "loading"],
    featured: false
  },
  {
    id: "krypton",
    name: "Krypton",
    icon: "🌐",
    shortDesc: "Optimizes Minecraft's networking stack. Lower latency, better multiplayer.",
    description: "Krypton is a Fabric mod that attempts to optimize the Minecraft networking stack. It includes several optimizations including network I/O improvements and packet compression, which reduces server latency and improves multiplayer performance.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "network",
    performanceRating: 70,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 2, max: 15, avg: 8 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 76,
    downloadUrl: "https://modrinth.com/mod/krypton",
    installInstructions: "Drop in mods folder. Works server-side too for best results. No configuration required.",
    tags: ["network", "multiplayer", "latency", "performance"],
    featured: false
  },
  {
    id: "memoryleakfix",
    name: "Memory Leak Fix",
    icon: "🩹",
    shortDesc: "Patches known Minecraft memory leaks. Prevents crashes on long sessions.",
    description: "Memory Leak Fix patches several known memory leaks in Minecraft that cause the game to use progressively more RAM over time. Without this mod, long gaming sessions can result in crashes due to out-of-memory errors, particularly problematic on Android devices with limited RAM.",
    versions: ["1.14", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "memory",
    performanceRating: 83,
    memoryUsage: "very-low",
    memoryMB: -128,
    fpsGain: { min: 5, max: 20, avg: 10 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 84,
    downloadUrl: "https://modrinth.com/mod/memoryleakfix",
    installInstructions: "Place in mods folder. Essential for long gaming sessions. Works across all major mod loaders.",
    tags: ["memory", "ram", "stability", "crashes", "mobile"],
    featured: false
  },
  {
    id: "c2me",
    name: "C2ME",
    icon: "🔄",
    shortDesc: "Concurrent Chunk Management Engine. Parallel chunk loading on multi-core CPUs.",
    description: "C2ME (Concurrent Chunk Management Engine) is designed to improve the performance of chunk loading by making chunk loading happen in parallel across multiple CPU cores. This is especially beneficial for devices with multi-core processors, making chunk loading much faster.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "worldgen",
    performanceRating: 80,
    memoryUsage: "medium",
    memoryMB: 64,
    fpsGain: { min: 10, max: 50, avg: 25 },
    compatibility: { arm64: true, arm32: false, x86: true },
    minAndroid: 10,
    minRAM: 3,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 77,
    downloadUrl: "https://modrinth.com/mod/c2me-fabric",
    installInstructions: "Requires at least 3 GB RAM allocation and a multi-core CPU. Drop in mods folder. May cause issues with some chunk-modifying mods.",
    tags: ["chunks", "multicore", "cpu", "loading"],
    featured: false
  },
  {
    id: "moreculling",
    name: "More Culling",
    icon: "🎯",
    shortDesc: "Advanced block face and leaf culling. Reduces draw calls significantly.",
    description: "More Culling is a mod that changes how block face and foliage culling works in Minecraft. By more aggressively culling faces and leaves that are not visible to the player, it reduces the number of draw calls and polygons rendered, leading to improved FPS especially in dense forests.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 79,
    memoryUsage: "low",
    memoryMB: -16,
    fpsGain: { min: 10, max: 40, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 9,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 74,
    downloadUrl: "https://modrinth.com/mod/moreculling",
    installInstructions: "Requires Fabric or Quilt with Fabric API. Place in mods folder. Works best alongside Sodium.",
    tags: ["rendering", "culling", "blocks", "fps"],
    featured: false
  },
  {
    id: "enhancedblockentities",
    name: "Enhanced Block Entities",
    icon: "📦",
    shortDesc: "Renders chests, beds, signs as baked models. Massive FPS gain near storage.",
    description: "Enhanced Block Entities (EBE) reduces block entity rendering time by converting them to use baked block models instead of entity models. This makes rendering chests, beds, signs, shulker boxes and other block entities much faster, particularly noticeable when you have many chests in a storage room.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 84,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 20, max: 120, avg: 45 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Best Graphics"],
    popularity: 82,
    downloadUrl: "https://modrinth.com/mod/ebe",
    installInstructions: "Requires Fabric and Sodium. Place in mods folder. Makes a noticeable difference in storage rooms and villages.",
    tags: ["rendering", "block-entities", "chests", "fps"],
    featured: false
  },
  {
    id: "fastquit",
    name: "FastQuit",
    icon: "🚪",
    shortDesc: "Return to the title screen instantly while world saves in background.",
    description: "FastQuit allows you to return to the title screen immediately when quitting a world, while the world continues saving in the background. This eliminates the frustrating wait when closing worlds, which is especially long on Android devices with slower storage.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 60,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 71,
    downloadUrl: "https://modrinth.com/mod/fastquit",
    installInstructions: "Drop in mods folder. No configuration needed. Makes quitting worlds significantly faster.",
    tags: ["utility", "quality-of-life", "loading", "saving"],
    featured: false
  },
  {
    id: "clumps",
    name: "Clumps",
    icon: "✨",
    shortDesc: "Groups XP orbs together. Reduces entity count and improves FPS.",
    description: "Clumps groups XP orbs together into a single entity, reducing the number of entities in the world and improving performance. This is especially noticeable when killing many mobs or mining ore, where hundreds of XP orbs can spawn and dramatically reduce FPS.",
    versions: ["1.12", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "logic",
    performanceRating: 72,
    memoryUsage: "low",
    memoryMB: -16,
    fpsGain: { min: 5, max: 60, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 79,
    downloadUrl: "https://modrinth.com/mod/clumps",
    installInstructions: "Place in mods folder. Works on all major loaders. Most noticeable during mob grinding or heavy mining.",
    tags: ["entities", "xp", "orbs", "performance"],
    featured: false
  },
  {
    id: "spark",
    name: "Spark",
    icon: "🔍",
    shortDesc: "Performance profiler. Identify exactly what's lagging your game.",
    description: "Spark is a performance profiling mod for Minecraft. It helps identify what's causing performance issues by providing detailed CPU profiling, memory reporting, and real-time performance monitoring. While not a performance mod itself, it helps you diagnose and fix performance problems.",
    versions: ["1.8", "1.12", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "utility",
    performanceRating: 55,
    memoryUsage: "neutral",
    memoryMB: 8,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 83,
    downloadUrl: "https://modrinth.com/mod/spark",
    installInstructions: "Drop in mods folder. Use /spark profiler start to begin profiling. Share results at spark.lucko.me for analysis.",
    tags: ["profiling", "debug", "utility", "diagnostic"],
    featured: false
  }
];

// Mod categories metadata
const MOD_CATEGORIES = {
  rendering: { label: "Rendering", icon: "🎨", color: "#818cf8" },
  memory:    { label: "Memory",    icon: "🧠", color: "#c084fc" },
  logic:     { label: "Game Logic",icon: "⚙️", color: "#fb923c" },
  worldgen:  { label: "World Gen", icon: "🌍", color: "#34d399" },
  network:   { label: "Network",   icon: "🌐", color: "#60a5fa" },
  battery:   { label: "Battery",   icon: "🔋", color: "#4ade80" },
  utility:   { label: "Utility",   icon: "🔧", color: "#f87171" },
  general:   { label: "General",   icon: "✨", color: "#22c55e" }
};

const MC_VERSIONS = ["1.21", "1.20", "1.19", "1.18", "1.17", "1.16", "1.12"];
const MOD_LOADERS = ["Fabric", "Quilt", "NeoForge", "Forge"];
const LAUNCHERS   = ["Mojo Launcher", "PojavLauncher", "Official Launcher", "Other"];
const ANDROID_VERSIONS = ["14", "13", "12", "11", "10", "9", "8"];
const RAM_OPTIONS = ["1 GB", "2 GB", "3 GB", "4 GB", "6 GB", "8 GB+"];
const CPU_ARCHS   = ["ARM64 (64-bit)", "ARM32 (32-bit)", "x86"];
const GPUS        = ["Adreno", "Mali", "PowerVR", "Other"];
const PERF_GOALS  = ["Maximum FPS", "Balanced", "Best Graphics", "Battery Saver"];

// Export for use in other scripts
if (typeof module !== 'undefined') module.exports = { MODS_DB, MOD_CATEGORIES, MC_VERSIONS, MOD_LOADERS, LAUNCHERS, ANDROID_VERSIONS, RAM_OPTIONS, CPU_ARCHS, GPUS, PERF_GOALS };
